// <auto-generated />
using System;
using BettingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BettingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("BettingAPI.Models.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PotentialReturn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stake")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("BettingAPI.Models.BetLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MatchId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Odds")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BetId");

                    b.HasIndex("MatchId");

                    b.ToTable("BetLines");
                });

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OddsA")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OddsB")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OddsDraw")
                        .HasColumnType("TEXT");

                    b.Property<int>("SportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TeamB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SportId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OddsA = 3.70m,
                            OddsB = 2.17m,
                            OddsDraw = 1.62m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 6, 1, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Arsenal",
                            TeamB = "Chelsea"
                        },
                        new
                        {
                            Id = 2,
                            OddsA = 2.75m,
                            OddsB = 4.87m,
                            OddsDraw = 1.28m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 7, 7, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Liverpool",
                            TeamB = "Manchester United"
                        },
                        new
                        {
                            Id = 3,
                            OddsA = 2.89m,
                            OddsB = 1.72m,
                            OddsDraw = 1.51m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 7, 17, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Manchester City",
                            TeamB = "Tottenham"
                        },
                        new
                        {
                            Id = 4,
                            OddsA = 4.02m,
                            OddsB = 4.38m,
                            OddsDraw = 4.06m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 5, 13, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Newcastle",
                            TeamB = "Aston Villa"
                        },
                        new
                        {
                            Id = 5,
                            OddsA = 4.69m,
                            OddsB = 4.76m,
                            OddsDraw = 3.18m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 8, 9, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "West Ham",
                            TeamB = "Brighton"
                        },
                        new
                        {
                            Id = 6,
                            OddsA = 1.22m,
                            OddsB = 2.05m,
                            OddsDraw = 2.97m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 6, 12, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Everton",
                            TeamB = "Fulham"
                        },
                        new
                        {
                            Id = 7,
                            OddsA = 3.71m,
                            OddsB = 3.30m,
                            OddsDraw = 3.05m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 5, 16, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Leeds",
                            TeamB = "Leicester"
                        },
                        new
                        {
                            Id = 8,
                            OddsA = 1.26m,
                            OddsB = 1.92m,
                            OddsDraw = 4.62m,
                            SportId = 1,
                            StartTime = new DateTime(2026, 4, 7, 18, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Southampton",
                            TeamB = "Crystal Palace"
                        },
                        new
                        {
                            Id = 9,
                            OddsA = 1.50m,
                            OddsB = 4.85m,
                            OddsDraw = 0m,
                            SportId = 2,
                            StartTime = new DateTime(2026, 4, 8, 23, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Lakers",
                            TeamB = "Warriors"
                        },
                        new
                        {
                            Id = 10,
                            OddsA = 3.83m,
                            OddsB = 2.61m,
                            OddsDraw = 0m,
                            SportId = 2,
                            StartTime = new DateTime(2026, 4, 9, 0, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Celtics",
                            TeamB = "Heat"
                        },
                        new
                        {
                            Id = 11,
                            OddsA = 1.21m,
                            OddsB = 4.44m,
                            OddsDraw = 0m,
                            SportId = 2,
                            StartTime = new DateTime(2026, 4, 5, 22, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Bulls",
                            TeamB = "Knicks"
                        },
                        new
                        {
                            Id = 12,
                            OddsA = 2.44m,
                            OddsB = 2.40m,
                            OddsDraw = 0m,
                            SportId = 2,
                            StartTime = new DateTime(2026, 4, 9, 21, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Nets",
                            TeamB = "76ers"
                        },
                        new
                        {
                            Id = 13,
                            OddsA = 3.51m,
                            OddsB = 1.65m,
                            OddsDraw = 0m,
                            SportId = 2,
                            StartTime = new DateTime(2026, 4, 7, 5, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Suns",
                            TeamB = "Mavericks"
                        },
                        new
                        {
                            Id = 14,
                            OddsA = 2.30m,
                            OddsB = 4.48m,
                            OddsDraw = 0m,
                            SportId = 2,
                            StartTime = new DateTime(2026, 4, 6, 12, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Clippers",
                            TeamB = "Nuggets"
                        },
                        new
                        {
                            Id = 15,
                            OddsA = 3.96m,
                            OddsB = 3.60m,
                            OddsDraw = 0m,
                            SportId = 3,
                            StartTime = new DateTime(2026, 4, 6, 15, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Patriots",
                            TeamB = "Jets"
                        },
                        new
                        {
                            Id = 16,
                            OddsA = 2.11m,
                            OddsB = 1.33m,
                            OddsDraw = 0m,
                            SportId = 3,
                            StartTime = new DateTime(2026, 4, 6, 22, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Cowboys",
                            TeamB = "Eagles"
                        },
                        new
                        {
                            Id = 17,
                            OddsA = 2.49m,
                            OddsB = 5.00m,
                            OddsDraw = 0m,
                            SportId = 3,
                            StartTime = new DateTime(2026, 4, 6, 2, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Packers",
                            TeamB = "Bears"
                        },
                        new
                        {
                            Id = 18,
                            OddsA = 4.84m,
                            OddsB = 1.66m,
                            OddsDraw = 0m,
                            SportId = 3,
                            StartTime = new DateTime(2026, 4, 6, 23, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Chiefs",
                            TeamB = "Broncos"
                        },
                        new
                        {
                            Id = 19,
                            OddsA = 4.61m,
                            OddsB = 4.69m,
                            OddsDraw = 0m,
                            SportId = 3,
                            StartTime = new DateTime(2026, 4, 8, 2, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Rams",
                            TeamB = "49ers"
                        },
                        new
                        {
                            Id = 20,
                            OddsA = 2.58m,
                            OddsB = 4.69m,
                            OddsDraw = 0m,
                            SportId = 3,
                            StartTime = new DateTime(2026, 4, 8, 12, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Bills",
                            TeamB = "Dolphins"
                        },
                        new
                        {
                            Id = 21,
                            OddsA = 4.52m,
                            OddsB = 3.94m,
                            OddsDraw = 0m,
                            SportId = 4,
                            StartTime = new DateTime(2026, 4, 8, 8, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Thunderbolt",
                            TeamB = "Night Fury"
                        },
                        new
                        {
                            Id = 22,
                            OddsA = 4.06m,
                            OddsB = 2.21m,
                            OddsDraw = 0m,
                            SportId = 4,
                            StartTime = new DateTime(2026, 4, 7, 4, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Silver Arrow",
                            TeamB = "Wild Spirit"
                        },
                        new
                        {
                            Id = 23,
                            OddsA = 2.05m,
                            OddsB = 4.01m,
                            OddsDraw = 0m,
                            SportId = 4,
                            StartTime = new DateTime(2026, 4, 5, 21, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Golden Mane",
                            TeamB = "Storm Runner"
                        },
                        new
                        {
                            Id = 24,
                            OddsA = 4.06m,
                            OddsB = 3.03m,
                            OddsDraw = 0m,
                            SportId = 4,
                            StartTime = new DateTime(2026, 4, 4, 23, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Rapid Hooves",
                            TeamB = "Shadow Dancer"
                        },
                        new
                        {
                            Id = 25,
                            OddsA = 2.19m,
                            OddsB = 1.40m,
                            OddsDraw = 0m,
                            SportId = 4,
                            StartTime = new DateTime(2026, 4, 5, 1, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Blaze Runner",
                            TeamB = "Iron Stallion"
                        },
                        new
                        {
                            Id = 26,
                            OddsA = 3.98m,
                            OddsB = 3.24m,
                            OddsDraw = 0m,
                            SportId = 5,
                            StartTime = new DateTime(2026, 4, 6, 12, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Max Verstappen",
                            TeamB = "Lewis Hamilton"
                        },
                        new
                        {
                            Id = 27,
                            OddsA = 2.47m,
                            OddsB = 2.47m,
                            OddsDraw = 0m,
                            SportId = 5,
                            StartTime = new DateTime(2026, 4, 6, 18, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Charles Leclerc",
                            TeamB = "Lando Norris"
                        },
                        new
                        {
                            Id = 28,
                            OddsA = 1.66m,
                            OddsB = 4.37m,
                            OddsDraw = 0m,
                            SportId = 5,
                            StartTime = new DateTime(2026, 4, 7, 8, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Fernando Alonso",
                            TeamB = "George Russell"
                        },
                        new
                        {
                            Id = 29,
                            OddsA = 2.15m,
                            OddsB = 1.52m,
                            OddsDraw = 0m,
                            SportId = 5,
                            StartTime = new DateTime(2026, 4, 7, 10, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Carlos Sainz",
                            TeamB = "Sergio Perez"
                        },
                        new
                        {
                            Id = 30,
                            OddsA = 2.92m,
                            OddsB = 1.88m,
                            OddsDraw = 0m,
                            SportId = 5,
                            StartTime = new DateTime(2026, 4, 5, 17, 1, 9, 0, DateTimeKind.Utc),
                            Status = "Scheduled",
                            TeamA = "Oscar Piastri",
                            TeamB = "Valtteri Bottas"
                        });
                });

            modelBuilder.Entity("BettingAPI.Models.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Football"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Basketball"
                        },
                        new
                        {
                            Id = 3,
                            Name = "American Football"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horse Racing"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Formula 1"
                        });
                });

            modelBuilder.Entity("BettingAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BettingAPI.Models.Bet", b =>
                {
                    b.HasOne("BettingAPI.Models.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BettingAPI.Models.BetLine", b =>
                {
                    b.HasOne("BettingAPI.Models.Bet", "Bet")
                        .WithMany("BetLines")
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BettingAPI.Models.Match", "Match")
                        .WithMany("BetLines")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bet");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.HasOne("BettingAPI.Models.Sport", "Sport")
                        .WithMany("Matches")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("BettingAPI.Models.Bet", b =>
                {
                    b.Navigation("BetLines");
                });

            modelBuilder.Entity("BettingAPI.Models.Match", b =>
                {
                    b.Navigation("BetLines");
                });

            modelBuilder.Entity("BettingAPI.Models.Sport", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("BettingAPI.Models.User", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
